command-config:
  commands:

  - id: ifconfig
    description: ifconfig
    command: /sbin/ifconfig

  - id: ls
    description: ls
    command: /bin/ls
    arguments: [-l]

  - id: sleep
    description: sleep 1
    command: /bin/sleep
    arguments: [1]

proxy-config:
  proxies:

  - id: test_proxy
    description: google proxy
    url: http://www.google.com
