command-config:
  commands:

  - id: ifconfig
    description: ifconfig
    command: /sbin/ifconfig

  - id: ls
    description: ls
    command: /bin/ls
    arguments: [-l]

  - id: sleep
    description: sleep 1
    command: /bin/sleep
    arguments: [1]

proxy-config:
  proxies:

  - id: test_proxy
    description: google proxy
    url: http://www.google.com

static-paths:
  paths:
  - path: /vnstat.html

spring:
  resources:
    static-locations: classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/webapp/,classpath:/public/,file:/Users/aaron/test/